apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  name: echo-server
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: echo.lvh.me
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: echo-server
            port:
              name: http

---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: echo-server
spec:
  selector:
    app.kubernetes.io/name: echo-server
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: echo-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: echo-server
    spec:
      containers:
      - name: echo-server
        image: ealen/echo-server
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
